---@class Info
---@field start_y integer
---@field center_x integer
---@field center_y integer
---@field screen_w integer
---@field screen_h integer
---@field font_size integer

---@class Utils
---@field DrawText function
---@field DrawColoredText function
---@field DrawCrosshair function
